import type { Metadata } from './metadata.js'

/** Deposit from self-custodial to custodial wallet */
export type Deposit = {
  /** randomly generated by the app or provided by custodian */
  id: string
  /** the custodial wallet deposited to */
  walletId: string
  /** the deposit onchain address or lightning invoice */
  destination: string
  /** unix seconds timestamp */
  timestamp: number
  /** sats transferred */
  amount: number
  metadata?: Metadata
}
