import type { Metadata } from './metadata.js'

/** Withdrawal from custodial to self-custodial wallet */
export type Withdrawal = {
  /** randomly generated by the app */
  id: string
  /** the custodial wallet withdrawn from */
  walletId: string
  /** onchain address or lightning invoice */
  destination: string
  /** unix seconds timestamp */
  timestamp: number
  /** sats transferred */
  amount: number
  /** sats fee charged for withdrawal */
  fee: number
  metadata?: Metadata
}
